package bank_management_system;

import javax.swing.*;
import java.awt.*;

//Download the JCalender jar file in you system
//https://repo1.maven.org/maven2/com/toedter/jcalendar/1.4/jcalendar-1.4.jar
//right click on bank_management_system and go to properties -> go to java Build path -> select class path -> click on add external jar files -> select the file from the download location -> apply and close
import java.awt.event.*;

public class Credentials extends JFrame implements ActionListener{
	
	long form_number;
	
	JTextField user_pin, IntPass;
    String AccountNumber = ""+Admin.allotAccountNumber();
    String DebitCardNumber;
    String CreditCardNumber;
    JButton next;
	
	private static final long serialVersionUID = 1L;
	public Credentials(long form_number)
	{
		this.form_number = form_number;
		
		setLayout(null);
		
		//PRINTS THE FORM NUMBER 
//		String newString = "APPLICATION FORM NO. 2 is : "+(String)formNumber;
//		System.out.println(newString);
		JLabel app_num= new JLabel("APPLICATION FORM NO. is : "+form_number);
		app_num.setFont(new Font("Raleway", Font.BOLD , 38));
		app_num.setBounds(180, 20, 800, 40);
		add(app_num);
		
		//PERSONAL DETAILS PAGE 2
		JLabel personal_details= new JLabel("Sensitive Details : Keep a copy at a safe place");
		personal_details.setFont(new Font("Raleway",Font.PLAIN , 34));
		personal_details.setBounds(40, 80 , 800, 45);
		add(personal_details);
		
		//ACCOUNT Number generated by the system
        //get the new account number from the database
		// AccountNumber=""+Admin.allotAccountNumber();
		JLabel acc_number = new JLabel("A/C Number          :    "+ AccountNumber);
		acc_number.setFont(new Font("Raleway", Font.PLAIN , 25));
		acc_number.setBounds(40, 150 , 360, 40);
		add(acc_number);
		
		// -< Give a system generated password to the user 
        //Ask for internet banking password form the user
		JLabel InternetBankingPassword = new JLabel("NewPassword       : ");
		InternetBankingPassword.setFont(new Font("Raleway", Font.PLAIN, 25));
		InternetBankingPassword.setBounds(40, 200 , 260, 40);
		add(InternetBankingPassword);

		IntPass = new JTextField("Enter strong password");
		IntPass.setFont(new Font("Raleway", Font.PLAIN ,15));
		IntPass.setBounds(290,205,400,30);
		add(IntPass);

        //get unique atm number from the database if user has opted for it 
		if(true) {
			DebitCardNumber = ""+Admin.allotDebitNumber();
		}
		
		JLabel DebitCard = new JLabel("ATM Card              :    "+ DebitCardNumber);
		DebitCard.setFont(new Font("Arial", Font.PLAIN, 25));
		DebitCard.setBounds(40, 250 , 360, 40);
		add(DebitCard);
		// -< DebitCard number generated from the sql server and later to be replace by the user
        //Allow user to set pin for the DebitCard
        JLabel pin = new JLabel("Enter pin :");
	    pin.setFont(new Font("Arial", Font.PLAIN, 25));
	    pin.setBounds(40, 300 , 160, 40);
		add(pin);
        //-< check for validation and add re-enter pin
        //get pin from the user
        user_pin = new JTextField("Enter 4 digit pin");
		user_pin.setFont(new Font("Raleway", Font.PLAIN ,15));
		user_pin.setBounds(290, 300 , 400, 30);
		add(user_pin);
//checked
		
		//creating a next button to move to the Home Login page Class name -> Login
		next = new JButton("Next");
		next.setBackground(Color.BLACK);
		next.setForeground(Color.WHITE);
		next.setFont(new Font("Raleway", Font.PLAIN, 20));
		next.setBounds(575, 720 , 150, 40);
		add(next);
		//adding a acdtion listner
		next.addActionListener(this);

		// default view of the application is set to right corner for easy view during developement,
		// later it should be aligned to center

		getContentPane().setBackground(Color.WHITE);
		setSize(900,800);
		setLocation(1020,10);
		setVisible(true);
	}
	public void actionPerformed(ActionEvent ae) {  
		
		//extract the values from the JTextFields
		String formno = "" + form_number;
        String UserPin = user_pin.getText();
        String internetPassword = IntPass.getText();  		
		try {
			if(UserPin == "Enter 4 digit pin" || internetPassword == "Enter strong password")
			{
				JOptionPane.showMessageDialog(null, "You need to enter UserPin and InternetBanking Password");
			}
			
			else
			{
                //HIT the database
				Conn c = new Conn();
				//Table name
				String table_name = "netbanking";
				//create table add_det(formno varchar(7), account_type varchar(20), aadhar varchar(20), pan varchar(20), permission varchar(7));
				String querry = "insert into "+table_name+" values ('"+formno+"','"+AccountNumber+"','"+DebitCardNumber+"','"+CreditCardNumber+"','"+UserPin+"','"+internetPassword+"');";
				if(c.s != null) {
					try {
						c.s.executeUpdate(querry);
						System.out.println("1 row added!");
					} catch (Exception e) {
						System.out.println(e);
						System.out.println("row could not be entered!");
					}
					
					
					}
				else {
					System.out.println("Null");
				}
				System.out.println("Account created successfully");
				setVisible(false);
				new Login().setVisible(true);						
			}
		}catch (Exception ax){
			System.err.println(ax);
		}
	}
	//to run the page individually uncomment the main method. Pass only negative values to keep a track of the record
	public static void main(String args [])
	{
		new Credentials(-12l);
	}
}
